whynotearth/shinta-mani-wild

- package.json
- src/@types/vue-content-placeholders/index.ts
- src/components/BaseArticlesList.vue
- src/components/BaseHeading.vue
- src/components/BaseQuote.vue
- src/components/HeroImage.vue
- src/main.ts
- src/styles/variables.scss
- src/views/Home.vue
- src/views/Listing.vue
- yarn.lock
> Add placeholder for contents

- src/views/Search.vue
Move the position of quote block to above of stories.  
If we need another quote block at the end of the stories section (I don't recommend this because if stories become long, the chance of seeing the second quote block is very low)
> search view - move quote block to above of stories section

- src/components/BaseBannerAction.vue
- src/components/BaseButton.vue
- src/views/Home.vue
- src/views/Search.vue
- add link of the "book now" button  
- add a gradient  
- make the title of banner section read from API  
#19
> fix banner section

- src/types.ts
> types - add story and resort types

- src/views/Home.vue
update image of press  
add the link to press page `/search/press`  
remove shadow  
#29
> update image of press, add link to press page

- src/components/BaseBannerAction.vue
- src/components/VideoPlayer.vue
- src/styles/global.scss
- src/styles/mixins.scss
- src/styles/variables.scss
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
add shadow to banner  
add a placeholder for home hero  
inc font-size of h1  
improve shift-down of quote  
move hero placeholder style to mixin  
use `featuredBackground` of API in home
> Minor stylings and fixes of homepage

- src/types.ts
- src/views/Home.vue
- connect home gallery and cards images to API
- fix hero background black
- fix types (change String to string and Number to number)
> connect more stuff in home to API, fix hero background black, fix types

- src/components/PageFooter.vue
Update columns and data based on the new design  
#26
> change footer columns and data

- src/components/PageFooter.vue
- src/views/Home.vue
- Fix footer links `href` #41 
- Fix home banner title
- Add category get method in resort (not in use yet)
> Fix content issues

- src/components/BaseBannerAction.vue
- src/components/BaseImageLink.vue
- src/components/BookingBar.vue
- src/views/Home.vue
Because it was a confusing name
> rename base-button to base-image-link

- src/components/BaseArticleListItem.vue
- src/components/BaseArticlesList.vue
- src/styles/global.scss
- src/styles/variables.scss
- src/views/Search.vue
- add story image
- add story video preview on hover
- change color of the read more link
- add article item component
> Add stories image and preview

- src/views/Contact.vue
- add icons
- update layout
- add copy
- add the link to google maps
- connect to API (featured image and description)
#36
> Fix contact page

- src/components/BaseArticleListItem.vue
Add 700ms delay on hover of stories, then load and show video.  
_A note on video previews_: The size of videos (for preview) is big, we should reduce it to under 250KB, cuz we want to show it immediately.
> article list item - add fade effect on hover for stories

- src/views/Home.vue
- src/views/Listing.vue
Fix height of placeholders in listing and home
> fix placeholders height in listing and home

- src/components/BookingBar.vue
- src/components/PageHeader.vue
- src/helpers.ts
- src/styles/bootstrap.scss
- src/styles/global.scss
- src/styles/variables.scss
- Add dropdown for tents in page header
- Fix spacing between header links 
#44
> Add dropdown for tents in page header

- src/components/PageFooter.vue
Footer:  
- disable subscribe link for now
- add link for "visit our..."
#41
> footer - update links

- src/components/PageHeader.vue
- src/styles/variables.scss
> Style dropdown

- src/components/BaseArticleListItem.vue
- Now we have no flashing at all. The poster is background and video preview fades on it.  
- Add transition for fade-out (on mouse leave)
#73
> stories - fix story preview flashing

- src/components/BaseArticlesList.vue
- src/types.ts
- src/views/Listing.vue
- src/views/Search.vue
> filter stories by having posterUrl

- src/components/BaseBannerAction.vue
- src/components/BaseCard.vue
- src/components/PageHeader.vue
- src/helpers.ts
- src/router.ts
- src/store-modules/category.ts
- src/store-modules/resort.ts
- src/store.ts
- src/styles/global.scss
- src/types.ts
- src/views/Contact.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
- add `/tents` route and view
- add category store module
- set width of the image in base-card
- add buttonText prop to bannerAction
We should update all links to `/search/tents` in database to `/tents` @paulchrisluke 
#63
> Add tents page

- src/components/BookingBar.vue
> booking-bar - stick booking bar to bottom

- src/components/BaseActionBar.vue
- src/components/BaseArticleListItem.vue
- src/components/BaseArticlesList.vue
- src/styles/global.scss
- src/styles/variables.scss
- src/views/Home.vue
- src/views/Search.vue
- change line-heights
- change font-family of titles except for h1 titles
#88
> change h2 and h3 font to Roboto

- src/components/PageHeader.vue
> rename wildlife alliance

- src/views/Home.vue
> update home cards text

- src/components/BaseArticleListItem.vue
- src/components/BaseArticlesList.vue
- src/helpers.ts
- src/router.ts
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Story.vue
- src/views/Tents.vue
- Fix stories don't match clicked cards #120
- Change route to stories page
- Fix link of featured tents in tents page
> Fix stories link and change route

- src/components/BaseImageLink.vue
- src/components/BookingBar.vue
- src/constants/booking.ts
- src/mixins.global.ts
- src/views/Home.vue
> Link book now buttons to cloudbeds

- src/components/StorySlider.vue
- src/router.ts
- src/views/Gallery.vue
- src/views/Listing.vue
- Add gallery using story-slider (images with 16:9 ratio)
- Improve hover and responsive style of slider
#116
> Add gallery for images

- src/components/BaseQuote.vue
- src/directives.global.ts
- src/styles/global.scss
- src/styles/variables.scss
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
> Quote redesign

- src/mixins/doodles.ts
- src/styles/global.scss
- src/styles/lib-aos.scss
- revert some previous configs
- set speed -2.5 for Rellax
- set transition of transform to 0
- cleanup unused codes in lib-aos
#113
> Fix doodles configs

- src/components/BaseActionBar.vue
- remove pricing from the yellow bar
- align title in the yellow bar
#101 #130
> booking-bar - fix style, disable showing price temporarily

- src/components/PageFooter.vue
#137 change footer font and remove text styling
> Footer changes

- src/components/BaseArticleListItem.vue
- src/components/PageFooter.vue
#139
-commented out the yellow heart "like" icon for all article list item
> Hide article <3 like

- src/components/BookingBar.vue
- src/components/PageFooter.vue
- src/constants/layout.ts
> responsive footer

- src/assets/img/icon-hamburger-menu.svg
- src/components/PageHeader.vue
- src/styles/global.scss
- src/styles/mixins.scss
- src/styles/variables.scss
- src/views/Contact.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
> responsive menu

- package.json
- src/assets/img/icon-hamburger-menu.svg
- src/components/BaseActionBar.vue
- src/components/BaseArticleListItem.vue
- src/components/BaseGalleryList.vue
- src/components/BaseHeading.vue
- src/components/BaseImageLink.vue
- src/components/BaseQuote.vue
- src/components/BookingBar.vue
- src/components/PageFooter.vue
- src/components/PageHeader.vue
- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/constants/layout.ts
- src/directives.global.ts
- src/mixins/doodles.ts
- src/router.ts
- src/styles/global.scss
- src/styles/lib-aos.scss
- src/styles/mixins.scss
- src/styles/variables.scss
- src/views/Contact.vue
- src/views/Gallery.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
- yarn.lock
> Merge staging to master

- src/styles/global.scss
Caused by doodle backgrounds  
#148
> Remove horizontal scroll in the mobile

- src/components/BaseArticlesList.vue
- src/components/BaseBannerAction.vue
- src/views/Search.vue
- number of stories per column in mobile
- banner title line height in mobile
#151
> fix responsive stories and banner

- src/components/StorySlider.vue
- Hide like button in story lightbox 
#155
> Hide story like

- src/components/BaseCard.vue
- src/styles/global.scss
#143 
- Changed perspective of base cards
> Perspective Shift

- src/components/StorySlider.vue
- src/views/Contact.vue
- Changed title font from contact page from shinta mani to roboto 
#141
> Change contact font

- src/components/PageHeader.vue
- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/constants/layout.ts
- src/helpers.ts
- src/mixins.global.ts
- src/router.ts
- src/styles/global.scss
- src/views/ChickenSink.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
> video-player - add native html5 player for homepage, change hero image

- src/components/VideoPlayer.vue
- src/views/Contact.vue
> video-player - remove poster and add player to contact page

- src/components/BaseArticleListItem.vue
- src/components/BaseArticlesList.vue
- src/components/BaseQuote.vue
- src/views/Search.vue
- src/views/Tents.vue
> Remove readmore from quote and story

- src/components/BaseArticleListItem.vue
- src/components/BaseCard.vue
- src/views/Home.vue
- src/views/Tents.vue
- card images in tents page now read from API, not static addresses
- featured stories in tents page images fixed
- featured stories in tents page title style now look like the search pages
#166
> fix tents page thumbnails

- src/components/BaseImageLink.vue
> hotfix gap in buttons

- public/index.html
- src/App.vue
- src/components/BookingBar.vue
- src/components/LoadingProgress.vue
- src/components/PageFooter.vue
- src/components/PageHeader.vue
- src/connection/ajax.ts
- src/mixins/loading.ts
- src/router.ts
- src/store-modules/loading.ts
- src/store.ts
- src/styles/global.scss
- src/styles/variables.scss
- src/views/ChickenSink.vue
- src/views/Contact.vue
- src/views/Gallery.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Story.vue
- src/views/Tents.vue
> add loading indicator

- src/components/PageHeader.vue
- update layout of the responsive nav
- add contact link
- make links scrollable in the nav
#186
> Fix responsive navigation

- src/main.ts
- src/views/Home.vue
- load banner image based on window size
- make the image visible in any window size
#185
> fix responsive press banner

- src/views/Story.vue
> hotfix responsive story

- src/components/BaseQuote.vue
- src/views/ChickenSink.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
> add quote card new design

- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/views/ChickenSink.vue
- src/views/Contact.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
- fix autoplay (set default to mute)  
- add a mute toggle button to player
- store mute status in local storage
#195 #191
> add mute to player

- src/components/BaseArticleListItem.vue
- src/views/Search.vue
- src/views/Tents.vue
> hotfix featured story cutoff

- src/components/BaseActionBar.vue
- src/components/BaseBannerAction.vue
- src/components/BaseButtonUI.vue
- src/components/BaseImageButton.vue
- src/components/BaseQuote.vue
- src/components/BookingBar.vue
- src/components/PageHeader.vue
- src/views/ChickenSink.vue
- src/views/Contact.vue
- src/views/Home.vue
- rewrite the buttons component to have different sizes
- fix the gap between parts of buttons (needs real device test)
- separate link and button components with abstraction of button-ui
- booking bar button x-small size
#184 #187
> rewrite buttons with different sizes

- src/components/StorySlider.vue
- src/styles/variables.scss
- src/views/Gallery.vue
- src/views/Story.vue
Story Lightbox Auto Resizing #218
> fix story and gallery responsive scroll and shadows

- src/components/LoadingProgress.vue
- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/styles/global.scss
- src/views/Contact.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
> autoplay on stories iphone, update poster in video-player

- src/views/Tents.vue
> fix font family  cards in tents

- src/components/PageHeader.vue
- src/views/Tents.vue
> remove view-tents button in header and mobile nav

- src/components/BaseLoadingSpinner.vue
- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/styles/global.scss
- src/views/ChickenSink.vue
- add loading animation to the video player
- enable preload on stories videos
- fix autoplay for next slides with sound on iOS _(by unmuting all videos at once when the user clicks on unmute button)_ https://dev.to/mort3za/how-to-fix-autoplay-html5-video-on-ios-4p39
#227 #233
> testing the loading issue in story videos, improvements to video player and story video

- src/components/StorySlider.vue
- src/mixins.global.ts
- src/mixins/vh-fix.ts
- src/styles/global.scss
> story - fix vh in iOS (scrollbars issue in stories and gallery)

- src/views/Contact.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
- Changed all Title font size from font-size-xl-huge to default H1 sizing
#260
> Changed all H1 from font-size-xl-huge to default H1 #260

- src/components/GallerySlider.vue
- src/views/Gallery.vue
- Cleanup image slider by moving it to a new component
- add autoplay in the image gallery
#267
> separate gallery and story sliders, enable autoplay in gallery

- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/views/Contact.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
Changes:
- Updated the q_auto setting in `VideoPlayer.vue` to `best` instead of `good`
- Enable loop in hero videos
- Use best quality in story videos too
#237
> Change Video Quality settings, Enable loop in hero videos

- src/components/VideoPlayer.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
- fix quote height bug
- fix alt of poster in video player
> fix quote height bug, fix alt of poster in video player

- src/views/Tents.vue
Changes:
- Added slider to /tents (`Tents.vue`)
- Added breakpoint for mobile
- When initilizing Swiper we make sure, that the element is in the DOM
#28
> Responsive slider

- src/components/BaseCard.vue
- src/views/Home.vue
> fix adjust mobile card spacing

- src/components/VideoPlayer.vue
- src/styles/global.scss
- src/styles/mixins.scss
- src/styles/variables.scss
> fix header videos alignment

- src/components/PageHeader.vue
- src/styles/global.scss
- Add animation to hamburger icon on open/close
- Add shadow to header when mobile nav is open
- Fix minor spacings
#234
> #234 Add animation for haburger menu

- src/components/BaseActionBar.vue
- src/components/BookingBar.vue
#279 
Also, use getPassiveEventConfig() + variable renames in bookingBar.vue.
> booking bar - fix font-size in mobile

- src/components/GallerySlider.vue
- src/components/StorySlider.vue
- Add custom tap areas for mobile navigation in story/gallery slider
#255
> story/gallery - fix tap areas for navigation in mobile

- src/components/BaseCard.vue
- src/mixins/doodles.ts
- src/styles/global.scss
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Tents.vue
- add 3d effect to doodle images
- improve the position of doodle images
#169
> doodles - Add tilt effect, improve position

- src/components/GallerySlider.vue
- src/components/StorySlider.vue
- src/components/VideoPlayer.vue
- src/styles/variables.scss
- enlarge gallery slides in desktop #251 
- load responsive images in gallery/story
> gallery/story - enlarge gallery slides in desktop, improve images

- src/App.vue
- src/components/BaseArticleListItem.vue
- src/components/BaseGalleryList.vue
- src/components/PageFooter.vue
- src/components/PageHeader.vue
- src/components/StorySlider.vue
- src/router.ts
- src/store-modules/loading.ts
- src/store-modules/resort.ts
- src/views/ChickenSink.vue
- src/views/Contact.vue
- src/views/Gallery.vue
- src/views/Home.vue
- src/views/Listing.vue
- src/views/Search.vue
- src/views/Story.vue
- src/views/Tents.vue
Fix issues related to router:  
- prevent refresh page components due to :key on routerView
- use `<router-link>` instead of pure hyperlinks
- restore scroll position on browser back/forward
[Bug] should cancel previous ajax requests on route change (fixed by changing store structure)
#297   
This was a prerequisite for #200
> fix router related issues

- src/components/VideoPlayer.vue
Temporarily disable video transformation in video player.
> Hotfix: disable video transformations in video player component
